BoxLayout:
    orientation: 'vertical'
    padding: 10
    spacing: 10

    TextInput:
        id: input_number
        text: '7'
        font_size: 48
        multiline: False
        halign: 'center'
        size_hint_y: None
        height: '50dp'

    Button:
        text: 'Square'
        font_size: 48
        on_press: app.handle_calculate(input_number.text)

    Label:
        id: output_label
        font_size: 48
        color: (0, 1, 1, 1)
        text: "Result will appear here"
