BoxLayout:
    orientation: 'vertical'


    Label:
        text: "Hello, Kivy!"
        font_size: 60
        size_hint_y: 0.2

    BoxLayout:
        orientation: 'horizontal'
        Button:
            text: "Up"
            on_press: app.handle_press(1)
        Button:
            text: "Down"
            on_press: app.handle_press(-1)

    Label:
        text: "I did this :)"
        size_hint_y: 0.1